version: "2"
services:
  elasticsearch:
    build: elasticsearch/
    ports:
      - 9200:9200
      - 9300:9300


  kibana:
    build: kibana/
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch


  miner:
    build: miner/
    links:
      - elasticsearch
    ports:
      - "5000:5000"
    volumes:
      - ".:/usr/src/app"
    depends_on:
      - elasticsearch
      - kibana
    privileged: true
