version: "2"
services:
  elasticsearch:
    image: "elasticsearch:alpine"
    ports:
      - 9200:9200
  redis:
    image: "redis:alpine"
  kibana:
    image: "kibana:latest"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
  miner:
    build: "."
    links:
      - redis
      - elasticsearch
    ports:
      - "5000:5000"
    volumes:
      - ".:/usr/src/app"
    depends_on:
      - elasticsearch
      - kibana
    privileged: true
